import { DashboardIssue } from "./types";

export function getDemoIssues(): DashboardIssue[] {
  return [
    // Issue #14 — scoped + green (Ready)
    {
      number: 14,
      title: "Fix health endpoint 500 error",
      body: "The health endpoint returns 500 when the database connection is unavailable, causing false positive alerts in our monitoring system.",
      labels: [{ name: "bug", color: "d73a4a" }],
      created_at: "2026-02-03T10:00:00Z",
      updated_at: "2026-02-05T14:30:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/14",
      status: "scoped",
      confidence: "green",
      scoping: {
        confidence: "green",
        confidence_reason:
          "Clear bug with existing test coverage and isolated code path",
        current_behavior:
          "The health endpoint returns 500 when the database connection is unavailable, causing false positive alerts.",
        requested_fix:
          "Return 200 with degraded status when database is unavailable. Include status details in response body.",
        files_to_modify: [
          "src/routes/health.ts",
          "src/services/database.ts",
          "tests/health.test.ts",
        ],
        tests_needed:
          "Add test for unreachable DB scenario, verify degraded response format",
        action_plan: [
          "Update error handler in health.ts",
          "Add try-catch for DB connection",
          "Add test for unreachable DB scenario",
        ],
        risks: [
          "Downstream services may depend on 500 status for alerting",
        ],
        open_questions: [],
      },
      files_info: [
        { path: "src/routes/health.ts", lines: 45 },
        { path: "src/services/database.ts", lines: 120 },
        { path: "tests/health.test.ts", lines: 85 },
      ],
      fix_progress: null,
      blocker: null,
      pr: null,
      messages: [],
      steps: [],
      scoping_session: null,
      fix_session: null,
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-05T14:30:00Z",
      fix_started_at: null,
      completed_at: null,
    },

    // Issue #17 — scoped + green (Ready, different issue)
    {
      number: 17,
      title: "Add input validation to POST /users",
      body: "POST /users endpoint accepts any input without validation. Need to validate email format and required fields.",
      labels: [
        { name: "enhancement", color: "a2eeef" },
        { name: "security", color: "e11d48" },
      ],
      created_at: "2026-02-01T08:00:00Z",
      updated_at: "2026-02-04T16:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/17",
      status: "scoped",
      confidence: "green",
      scoping: {
        confidence: "green",
        confidence_reason:
          "Well-defined requirements with clear validation patterns in codebase",
        current_behavior:
          "POST /users accepts any JSON body without validation. Invalid emails and missing required fields are stored in the database.",
        requested_fix:
          "Add Zod schema validation for email, name, and role fields. Return 400 with field-level errors for invalid input.",
        files_to_modify: ["src/routes/users.ts", "src/schemas/user.ts"],
        tests_needed: "Add validation test cases for each field",
        action_plan: [
          "Create Zod schema in user.ts",
          "Add validation middleware to POST handler",
          "Add error response formatting",
        ],
        risks: [],
        open_questions: [],
      },
      files_info: [
        { path: "src/routes/users.ts", lines: 78 },
        { path: "src/schemas/user.ts", lines: null },
      ],
      fix_progress: null,
      blocker: null,
      pr: null,
      messages: [],
      steps: [],
      scoping_session: null,
      fix_session: null,
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-04T16:00:00Z",
      fix_started_at: null,
      completed_at: null,
    },

    // Issue #21 — scoped + yellow (Needs Input)
    {
      number: 21,
      title: "Migrate database to PostgreSQL",
      body: "We need to migrate from SQLite to PostgreSQL for production. This involves schema changes, connection pooling, and migration scripts.",
      labels: [{ name: "infrastructure", color: "0075ca" }],
      created_at: "2026-01-28T12:00:00Z",
      updated_at: "2026-02-03T09:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/21",
      status: "scoped",
      confidence: "yellow",
      scoping: {
        confidence: "yellow",
        confidence_reason:
          "Devin has questions about migration constraints and data validation requirements",
        current_behavior:
          "Application uses SQLite via better-sqlite3 for all data storage. SQLite lacks concurrent write support and has a 2GB practical size limit, causing lock contention under load.",
        requested_fix:
          "Migrate to PostgreSQL with connection pooling via pg-pool. Create migration scripts for all existing tables and seed data.",
        files_to_modify: [
          "src/config/database.ts",
          "db/migrations/001_create_tables.sql",
          "db/migrations/002_seed_data.sql",
          "src/services/database.ts",
        ],
        tests_needed: "Migration tests and rollback verification",
        action_plan: [
          "Create PostgreSQL migration scripts for all tables",
          "Update database.ts to use pg-pool instead of better-sqlite3",
          "Add rollback scripts for each migration step",
        ],
        risks: ["Data loss if migration script fails mid-way"],
        open_questions: [
          "Should the migration preserve SQLite as a fallback for local development, or fully replace it?",
          "What are the schema constraints for foreign keys — should they use CASCADE or RESTRICT on delete?",
        ],
      },
      files_info: [
        { path: "src/config/database.ts", lines: 45 },
        { path: "db/migrations/001_create_tables.sql", lines: null },
        { path: "src/services/database.ts", lines: 120 },
      ],
      fix_progress: null,
      blocker: null,
      pr: null,
      messages: [],
      steps: [],
      scoping_session: null,
      fix_session: null,
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-03T09:00:00Z",
      fix_started_at: null,
      completed_at: null,
    },

    // Issue #9 — scoped + yellow (Needs Input)
    {
      number: 9,
      title: "Add rate limiting middleware",
      body: "We need rate limiting to prevent API abuse. Should support per-IP and per-user limits with configurable windows.",
      labels: [{ name: "enhancement", color: "a2eeef" }],
      created_at: "2026-01-25T15:00:00Z",
      updated_at: "2026-02-02T11:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/9",
      status: "scoped",
      confidence: "yellow",
      scoping: {
        confidence: "yellow",
        confidence_reason:
          "Need clarification on rate limit thresholds and storage backend",
        current_behavior: "No rate limiting exists on any endpoints.",
        requested_fix:
          "Add configurable rate limiting middleware with Redis or in-memory storage.",
        files_to_modify: [
          "src/middleware/rateLimit.ts",
          "src/config.ts",
          "src/index.ts",
          "tests/rateLimit.test.ts",
        ],
        tests_needed: "Rate limit enforcement and bypass tests",
        action_plan: [
          "Create rate limit middleware",
          "Add configuration for thresholds",
          "Wire middleware into Express app",
          "Add tests",
        ],
        risks: ["Could block legitimate users if thresholds are too low"],
        open_questions: [
          "What are the desired rate limits (requests per minute)?",
          "Should rate limiting use Redis or in-memory storage?",
        ],
      },
      files_info: [
        { path: "src/middleware/rateLimit.ts", lines: null },
        { path: "src/config.ts", lines: 35 },
        { path: "src/index.ts", lines: 89 },
        { path: "tests/rateLimit.test.ts", lines: null },
      ],
      fix_progress: null,
      blocker: null,
      pr: null,
      messages: [],
      steps: [],
      scoping_session: null,
      fix_session: null,
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-02T11:00:00Z",
      fix_started_at: null,
      completed_at: null,
    },

    // Issue #5 — scoped + red (Unclear)
    {
      number: 5,
      title: "Optimize database queries",
      body: "Database queries are slow. Need optimization.",
      labels: [{ name: "performance", color: "fbca04" }],
      created_at: "2026-01-20T09:00:00Z",
      updated_at: "2026-02-01T14:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/5",
      status: "scoped",
      confidence: "red",
      scoping: {
        confidence: "red",
        confidence_reason:
          "Vague issue with no reproduction steps, metrics, or clear scope",
        current_behavior: "Not clearly described in the issue",
        requested_fix:
          "Unable to determine without more information",
        files_to_modify: [],
        tests_needed: "Unable to determine",
        action_plan: [
          "Insufficient information to create a plan",
        ],
        risks: [],
        open_questions: [
          "What specific behavior is expected after the migration?",
          "Which tables need to be migrated and what are the schema constraints?",
        ],
      },
      files_info: [],
      fix_progress: null,
      blocker: null,
      pr: null,
      messages: [],
      steps: [],
      scoping_session: null,
      fix_session: null,
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-01T14:00:00Z",
      fix_started_at: null,
      completed_at: null,
    },

    // Issue #12 — scoped + red (Unclear)
    {
      number: 12,
      title: "Improve error handling across services",
      body: "Error handling is inconsistent. Some services throw, others return null. Need a unified approach.",
      labels: [{ name: "refactor", color: "d4c5f9" }],
      created_at: "2026-01-22T11:00:00Z",
      updated_at: "2026-02-01T10:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/12",
      status: "scoped",
      confidence: "red",
      scoping: {
        confidence: "red",
        confidence_reason:
          "Scope is too broad — touches 15+ files without clear priority",
        current_behavior:
          "Inconsistent error handling across services — some throw, some return null.",
        requested_fix:
          "Unable to determine without defining error handling strategy first.",
        files_to_modify: [],
        tests_needed: "Unable to determine",
        action_plan: [
          "Insufficient information — need error handling strategy defined first",
        ],
        risks: [
          "Breaking changes across all services if approach changes",
        ],
        open_questions: [
          "Should services use Result types, throw exceptions, or return error objects?",
          "Which services are highest priority to fix first?",
        ],
      },
      files_info: [],
      fix_progress: null,
      blocker: null,
      pr: null,
      messages: [],
      steps: [],
      scoping_session: null,
      fix_session: null,
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-01T10:00:00Z",
      fix_started_at: null,
      completed_at: null,
    },

    // Issue #7 — fixing (in progress)
    {
      number: 7,
      title: "Fix CORS configuration for API",
      body: "CORS headers are not set correctly, causing cross-origin requests to fail from the frontend.",
      labels: [{ name: "bug", color: "d73a4a" }],
      created_at: "2026-02-04T10:00:00Z",
      updated_at: "2026-02-07T08:30:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/7",
      status: "fixing",
      confidence: "green",
      scoping: {
        confidence: "green",
        confidence_reason: "Clear bug with straightforward fix",
        current_behavior:
          "API responses lack Access-Control-Allow-Origin and related CORS headers. Browsers block all cross-origin requests from the frontend (localhost:5173) to the API (localhost:3000), causing fetch failures.",
        requested_fix:
          "Add CORS middleware that sets Access-Control-Allow-Origin, Allow-Methods, and Allow-Headers. Support configurable allowed origins from environment variable.",
        files_to_modify: [
          "src/middleware/cors.ts",
          "src/config.ts",
          "src/index.ts",
          "tests/cors.test.ts",
        ],
        tests_needed: "CORS header verification tests for allowed and blocked origins",
        action_plan: [
          "Create CORS middleware with configurable origin allowlist",
          "Add ALLOWED_ORIGINS to config.ts with env var support",
          "Wire CORS middleware into Express app before routes",
        ],
        risks: [],
        open_questions: [],
      },
      files_info: [
        { path: "src/middleware/cors.ts", lines: 25 },
        { path: "src/config.ts", lines: 35 },
        { path: "src/index.ts", lines: 89 },
      ],
      fix_progress: {
        status: "in_progress",
        current_step: "Add try-catch for DB connection",
        completed_steps: ["Update error handler in health.ts"],
        pr_url: null,
        blockers: [],
      },
      blocker: null,
      pr: null,
      messages: [],
      steps: [
        { label: "Update error handler in health.ts", status: "done" },
        {
          label: "Add try-catch for DB connection",
          status: "in_progress",
        },
        {
          label: "Add test for unreachable DB scenario",
          status: "pending",
        },
      ],
      scoping_session: {
        session_id: "demo-scope-7",
        session_url: "https://app.devin.ai/sessions/demo-scope-7",
        started_at: "2026-02-06T10:00:00Z",
      },
      fix_session: {
        session_id: "demo-fix-7",
        session_url: "https://app.devin.ai/sessions/demo-fix-7",
        started_at: "2026-02-07T08:00:00Z",
      },
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-06T10:15:00Z",
      fix_started_at: "2026-02-07T08:00:00Z",
      completed_at: null,
    },

    // Issue #8 — pr_open
    {
      number: 8,
      title: "Fix memory leak in WebSocket handler",
      body: "WebSocket connections are not being cleaned up properly, causing memory to grow over time.",
      labels: [{ name: "bug", color: "d73a4a" }],
      created_at: "2026-02-02T09:00:00Z",
      updated_at: "2026-02-06T16:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/8",
      status: "pr_open",
      confidence: "green",
      scoping: {
        confidence: "green",
        confidence_reason: "Clear memory leak with identifiable source in WebSocket handler",
        current_behavior:
          "WebSocket connections are not being cleaned up on disconnect. Event listeners accumulate on the server, and the connection pool grows unbounded. Memory usage increases ~50MB/hour under normal traffic.",
        requested_fix:
          "Add proper cleanup in the disconnect handler: remove all event listeners, release pool slot, and implement a max connection limit with graceful rejection.",
        files_to_modify: [
          "src/ws/handler.ts",
          "src/ws/pool.ts",
          "tests/ws.test.ts",
        ],
        tests_needed: "Memory leak regression test, connection pool limit test",
        action_plan: [
          "Add removeAllListeners() call in disconnect handler",
          "Implement connection pool with max limit and cleanup",
          "Add regression test verifying listeners are freed on disconnect",
        ],
        risks: [],
        open_questions: [],
      },
      files_info: [
        { path: "src/ws/handler.ts", lines: 95 },
        { path: "src/ws/pool.ts", lines: 60 },
        { path: "tests/ws.test.ts", lines: 85 },
      ],
      fix_progress: {
        status: "completed",
        current_step: "Add test for unreachable DB scenario",
        completed_steps: [
          "Update error handler in health.ts",
          "Add try-catch for DB connection",
          "Add test for unreachable DB scenario",
        ],
        pr_url:
          "https://github.com/natan/devin-issue-pilot-demo/pull/42",
        blockers: [],
      },
      blocker: null,
      pr: {
        url: "https://github.com/natan/devin-issue-pilot-demo/pull/42",
        number: 42,
        title:
          "Fix: Return degraded status from /health when DB is unavailable",
        branch: "feature/fix-health-endpoint",
        files_changed: [
          {
            path: "src/routes/health.ts",
            additions: 12,
            deletions: 4,
            is_new: false,
            diff_lines: [
              { type: "remove", content: "  return res.status(500).json({ error: 'DB unreachable' });", oldLine: 42 },
              { type: "add", content: "  try {", newLine: 42 },
              { type: "add", content: "    await db.healthCheck();", newLine: 43 },
              { type: "add", content: "    return res.json({ status: 'healthy', db: 'connected' });", newLine: 44 },
              { type: "add", content: "  } catch (err) {", newLine: 45 },
              { type: "add", content: "    return res.json({", newLine: 46 },
              { type: "add", content: "      status: 'degraded',", newLine: 47 },
              { type: "add", content: "      db: 'unavailable',", newLine: 48 },
              { type: "add", content: "      error: err.message,", newLine: 49 },
              { type: "add", content: "    });", newLine: 50 },
              { type: "add", content: "  }", newLine: 51 },
            ],
          },
          {
            path: "src/services/database.ts",
            additions: 8,
            deletions: 2,
            is_new: false,
            diff_lines: [
              { type: "context", content: "export class Database {", oldLine: 15, newLine: 15 },
              { type: "add", content: "  async healthCheck(): Promise<boolean> {", newLine: 16 },
              { type: "add", content: "    const client = await this.pool.connect();", newLine: 17 },
              { type: "add", content: "    try {", newLine: 18 },
              { type: "add", content: "      await client.query('SELECT 1');", newLine: 19 },
              { type: "add", content: "      return true;", newLine: 20 },
              { type: "add", content: "    } finally {", newLine: 21 },
              { type: "add", content: "      client.release();", newLine: 22 },
              { type: "add", content: "    }", newLine: 23 },
              { type: "add", content: "  }", newLine: 24 },
              { type: "context", content: "}", oldLine: 16, newLine: 25 },
            ],
          },
          {
            path: "tests/health.test.ts",
            additions: 24,
            deletions: 0,
            is_new: true,
            diff_lines: [
              { type: "add", content: "import { describe, it, expect } from 'vitest';", newLine: 1 },
              { type: "add", content: "import { createApp } from '../src/app';", newLine: 2 },
              { type: "add", content: "", newLine: 3 },
              { type: "add", content: "describe('GET /health', () => {", newLine: 4 },
              { type: "add", content: "  it('returns degraded when DB is down', async () => {", newLine: 5 },
              { type: "add", content: "    const app = createApp({ dbUrl: 'invalid' });", newLine: 6 },
              { type: "add", content: "    const res = await app.inject({ url: '/health' });", newLine: 7 },
              { type: "add", content: "    expect(res.statusCode).toBe(200);", newLine: 8 },
              { type: "add", content: "    expect(res.json().status).toBe('degraded');", newLine: 9 },
              { type: "add", content: "  });", newLine: 10 },
              { type: "add", content: "});", newLine: 11 },
            ],
          },
        ],
      },
      messages: [],
      steps: [
        { label: "Update error handler in health.ts", status: "done" },
        { label: "Add try-catch for DB connection", status: "done" },
        {
          label: "Add test for unreachable DB scenario",
          status: "done",
        },
      ],
      scoping_session: {
        session_id: "demo-scope-8",
        session_url: "https://app.devin.ai/sessions/demo-scope-8",
        started_at: "2026-02-05T10:00:00Z",
      },
      fix_session: {
        session_id: "demo-fix-8",
        session_url: "https://app.devin.ai/sessions/demo-fix-8",
        started_at: "2026-02-06T14:00:00Z",
        updated_at: "2026-02-06T14:06:14Z",
      },
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-05T10:10:00Z",
      fix_started_at: "2026-02-06T14:00:00Z",
      completed_at: "2026-02-06T16:00:00Z",
    },

    // Issue #3 — blocked
    {
      number: 3,
      title: "Add OAuth2 login flow",
      body: "Implement OAuth2 login with GitHub as the identity provider. Users should be redirected to GitHub for authentication.",
      labels: [{ name: "feature", color: "0e8a16" }],
      created_at: "2026-01-30T14:00:00Z",
      updated_at: "2026-02-07T09:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/3",
      status: "blocked",
      confidence: "green",
      scoping: {
        confidence: "green",
        confidence_reason: "Well-defined OAuth2 flow with clear implementation path",
        current_behavior:
          "No authentication exists. All API endpoints are publicly accessible. Users cannot log in or have their identity verified.",
        requested_fix:
          "Add GitHub OAuth2 login flow: redirect to GitHub, exchange code for token, store session in cookie, protect routes with auth middleware.",
        files_to_modify: [
          "src/routes/auth.ts",
          "src/middleware/auth.ts",
          "src/config.ts",
          "src/routes/login.ts",
        ],
        tests_needed: "OAuth flow integration tests, session cookie validation tests",
        action_plan: [
          "Create /auth/github route for OAuth redirect and callback",
          "Add session middleware with signed cookies and token storage",
          "Create auth guard middleware for protected routes",
        ],
        risks: [],
        open_questions: [],
      },
      files_info: [
        { path: "src/routes/auth.ts", lines: null },
        { path: "src/middleware/auth.ts", lines: null },
        { path: "src/routes/login.ts", lines: null },
        { path: "src/config.ts", lines: 35 },
      ],
      fix_progress: {
        status: "blocked",
        current_step: "Add try-catch for DB connection",
        completed_steps: ["Update error handler in health.ts"],
        pr_url: null,
        blockers: [
          "The database.ts file uses a custom connection pool wrapper (DBPool) that doesn't expose a standard health check method.",
        ],
      },
      blocker: {
        what_happened:
          "The database.ts file uses a custom connection pool wrapper (DBPool) that doesn\u2019t expose a standard health check method. The try-catch approach won\u2019t work without modifying the pool interface.",
        suggestion:
          "Add a .isHealthy() method to the DBPool class. This would require modifying src/lib/pool.ts \u2014 a new file not in the original plan.",
      },
      pr: null,
      messages: [],
      steps: [
        { label: "Update error handler in health.ts", status: "done" },
        {
          label: "Add try-catch for DB connection",
          status: "blocked",
        },
        {
          label: "Add test for unreachable DB scenario",
          status: "pending",
        },
      ],
      scoping_session: {
        session_id: "demo-scope-3",
        session_url: "https://app.devin.ai/sessions/demo-scope-3",
        started_at: "2026-02-06T08:00:00Z",
      },
      fix_session: {
        session_id: "demo-fix-3",
        session_url: "https://app.devin.ai/sessions/demo-fix-3",
        started_at: "2026-02-07T08:30:00Z",
      },
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-06T08:10:00Z",
      fix_started_at: "2026-02-07T08:30:00Z",
      completed_at: null,
    },

    // Issue #10 — timed_out
    {
      number: 10,
      title: "Implement webhook delivery system",
      body: "Build a webhook delivery system with retry logic and delivery tracking.",
      labels: [{ name: "feature", color: "0e8a16" }],
      created_at: "2026-01-29T10:00:00Z",
      updated_at: "2026-02-06T12:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/10",
      status: "timed_out",
      confidence: "green",
      scoping: {
        confidence: "green",
        confidence_reason: "Clear requirements but large scope",
        current_behavior: "No webhook system exists.",
        requested_fix:
          "Implement webhook registration, delivery queue, retry logic, and delivery logs.",
        files_to_modify: [
          "src/services/webhooks.ts",
          "src/routes/webhooks.ts",
          "src/queue/delivery.ts",
        ],
        tests_needed: "Webhook delivery and retry tests",
        action_plan: [
          "Create webhook registration endpoint",
          "Build delivery queue",
          "Add retry logic with exponential backoff",
        ],
        risks: ["Complex queue system may be overkill"],
        open_questions: [],
      },
      files_info: [
        { path: "src/services/webhooks.ts", lines: null },
        { path: "src/routes/webhooks.ts", lines: null },
        { path: "src/queue/delivery.ts", lines: null },
      ],
      fix_progress: null,
      blocker: null,
      pr: null,
      messages: [],
      steps: [
        { label: "Create webhook registration endpoint", status: "done" },
        { label: "Build delivery queue", status: "pending" },
        {
          label: "Add retry logic with exponential backoff",
          status: "pending",
        },
      ],
      scoping_session: null,
      fix_session: {
        session_id: "demo-fix-10",
        session_url: "https://app.devin.ai/sessions/demo-fix-10",
        started_at: "2026-02-06T11:30:00Z",
        updated_at: "2026-02-06T12:00:00Z",
      },
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-05T10:00:00Z",
      fix_started_at: "2026-02-06T11:30:00Z",
      completed_at: null,
    },

    // Issue #11 — aborted
    {
      number: 11,
      title: "Add GraphQL API layer",
      body: "Add a GraphQL layer on top of the existing REST API for more flexible client queries.",
      labels: [{ name: "feature", color: "0e8a16" }],
      created_at: "2026-01-27T09:00:00Z",
      updated_at: "2026-02-05T15:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/11",
      status: "aborted",
      confidence: "green",
      scoping: {
        confidence: "green",
        confidence_reason: "Clear pattern but scope was too large",
        current_behavior: "REST-only API.",
        requested_fix: "Add GraphQL schema and resolvers alongside REST.",
        files_to_modify: [
          "src/graphql/schema.ts",
          "src/graphql/resolvers.ts",
          "src/index.ts",
        ],
        tests_needed: "GraphQL query and mutation tests",
        action_plan: [
          "Set up Apollo Server",
          "Define GraphQL schema",
          "Implement resolvers",
        ],
        risks: ["Maintaining two API surfaces increases complexity"],
        open_questions: [],
      },
      files_info: [
        { path: "src/graphql/schema.ts", lines: null },
        { path: "src/graphql/resolvers.ts", lines: null },
      ],
      fix_progress: null,
      blocker: null,
      pr: null,
      messages: [],
      steps: [
        { label: "Set up Apollo Server", status: "done" },
        { label: "Define GraphQL schema", status: "done" },
        { label: "Implement resolvers", status: "pending" },
      ],
      scoping_session: null,
      fix_session: {
        session_id: "demo-fix-11",
        session_url: "https://app.devin.ai/sessions/demo-fix-11",
        started_at: "2026-02-05T14:00:00Z",
        updated_at: "2026-02-05T14:45:00Z",
      },
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-04T09:00:00Z",
      fix_started_at: "2026-02-05T14:00:00Z",
      completed_at: null,
    },

    // Issue #15 — failed
    {
      number: 15,
      title: "Fix rate limiter middleware",
      body: "The rate limiter is using a fixed-window algorithm that allows burst traffic at window boundaries. Need to switch to a token bucket approach.",
      labels: [{ name: "bug", color: "d73a4a" }],
      created_at: "2026-02-01T11:00:00Z",
      updated_at: "2026-02-07T10:30:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/15",
      status: "failed",
      confidence: "green",
      scoping: {
        confidence: "green",
        confidence_reason:
          "Clear bug with well-defined fix — swap fixed-window for token bucket algorithm",
        current_behavior:
          "Rate limiter uses fixed-window counting, allowing 2x burst traffic at window boundaries. Clients can send 200 req/min instead of the intended 100 by timing requests across the reset boundary.",
        requested_fix:
          "Replace fixed-window counter with token bucket algorithm. Tokens refill at a steady rate, preventing boundary bursts while maintaining the same average limit.",
        files_to_modify: [
          "src/middleware/rateLimit.ts",
          "src/lib/tokenBucket.ts",
          "tests/rateLimit.test.ts",
        ],
        tests_needed: "Token bucket refill tests, burst prevention tests",
        action_plan: [
          "Analyze current rate limiter code and identify fixed-window logic",
          "Implement token bucket class in tokenBucket.ts",
          "Apply fix to middleware/rateLimit.ts to use token bucket",
        ],
        risks: [
          "Timing-sensitive tests may break due to token refill intervals",
        ],
        open_questions: [],
      },
      files_info: [
        { path: "src/middleware/rateLimit.ts", lines: 67 },
        { path: "src/lib/tokenBucket.ts", lines: null },
        { path: "tests/rateLimit.test.ts", lines: 142 },
      ],
      fix_progress: {
        status: "blocked",
        current_step: "Apply fix to middleware/rateLimit.ts to use token bucket",
        completed_steps: [
          "Analyze current rate limiter code and identify fixed-window logic",
          "Implement token bucket class in tokenBucket.ts",
        ],
        pr_url: null,
        blockers: [
          "Test suite failed: 3 assertions broken after change. The token bucket algorithm change caused timing-sensitive tests to fail intermittently.",
        ],
      },
      blocker: null,
      pr: null,
      messages: [],
      steps: [
        {
          label: "Analyzed rate limiter code",
          status: "done",
        },
        {
          label: "Identified token bucket implementation",
          status: "done",
        },
        {
          label: "Apply fix to middleware/rateLimit.ts",
          status: "failed",
        },
      ],
      scoping_session: {
        session_id: "demo-scope-15",
        session_url: "https://app.devin.ai/sessions/demo-scope-15",
        started_at: "2026-02-06T09:00:00Z",
      },
      fix_session: {
        session_id: "demo-fix-15",
        session_url: "https://app.devin.ai/sessions/demo-fix-15",
        started_at: "2026-02-07T09:30:00Z",
        updated_at: "2026-02-07T10:15:00Z",
      },
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-06T09:12:00Z",
      fix_started_at: "2026-02-07T09:30:00Z",
      completed_at: null,
    },

    // Issue #16 — done (completed, PR already merged)
    {
      number: 16,
      title: "Fix broken CI pipeline",
      body: "The CI pipeline fails on the lint step because of outdated ESLint config after the TypeScript 5 upgrade.",
      labels: [{ name: "bug", color: "d73a4a" }, { name: "ci", color: "0075ca" }],
      created_at: "2026-02-01T10:00:00Z",
      updated_at: "2026-02-05T12:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/16",
      status: "done",
      confidence: "green",
      scoping: {
        confidence: "green",
        confidence_reason:
          "Clear CI failure with straightforward config fix",
        current_behavior:
          "CI pipeline fails on lint step with 12 ESLint errors. All errors are related to deprecated rules from the TypeScript 5 migration.",
        requested_fix:
          "Update .eslintrc.json to use @typescript-eslint/recommended v6 rules. Remove deprecated rules and add new equivalents.",
        files_to_modify: [
          ".eslintrc.json",
          "tsconfig.json",
        ],
        tests_needed: "Verify CI pipeline passes with updated config",
        action_plan: [
          "Update ESLint config to v6 recommended rules",
          "Remove deprecated rule overrides",
          "Verify lint passes locally before push",
        ],
        risks: [],
        open_questions: [],
      },
      files_info: [
        { path: ".eslintrc.json", lines: 42 },
        { path: "tsconfig.json", lines: 28 },
      ],
      fix_progress: {
        status: "completed",
        current_step: "Verify lint passes locally before push",
        completed_steps: [
          "Update ESLint config to v6 recommended rules",
          "Remove deprecated rule overrides",
          "Verify lint passes locally before push",
        ],
        pr_url: null,
        blockers: [],
      },
      blocker: null,
      pr: null,
      messages: [],
      steps: [
        { label: "Update ESLint config to v6 recommended rules", status: "done" },
        { label: "Remove deprecated rule overrides", status: "done" },
        { label: "Verify lint passes locally before push", status: "done" },
      ],
      scoping_session: {
        session_id: "demo-scope-16",
        session_url: "https://app.devin.ai/sessions/demo-scope-16",
        started_at: "2026-02-04T10:00:00Z",
      },
      fix_session: {
        session_id: "demo-fix-16",
        session_url: "https://app.devin.ai/sessions/demo-fix-16",
        started_at: "2026-02-05T10:00:00Z",
        updated_at: "2026-02-05T10:08:30Z",
      },
      last_devin_comment_id: null,
      last_devin_comment_at: null,
      github_comment_url: null,
      forwarded_comment_ids: [],
      scoped_at: "2026-02-04T10:08:00Z",
      fix_started_at: "2026-02-05T10:00:00Z",
      completed_at: "2026-02-05T12:00:00Z",
    },

    // Issue #20 — awaiting_reply (scoping questions posted on GitHub)
    {
      number: 20,
      title: "Add WebSocket support for real-time notifications",
      body: "Users need real-time notifications when background jobs complete. Currently they have to refresh the page to see updates.",
      labels: [{ name: "feature", color: "0e8a16" }],
      created_at: "2026-02-02T09:00:00Z",
      updated_at: "2026-02-07T11:00:00Z",
      github_url: "https://github.com/natan/devin-issue-pilot-demo/issues/20",
      status: "awaiting_reply",
      confidence: "yellow",
      scoping: {
        confidence: "yellow",
        confidence_reason:
          "WebSocket implementation path is clear, but several architectural decisions need user input",
        current_behavior:
          "Users must manually refresh the page to see updates from background jobs. There is no push mechanism for real-time notifications.",
        requested_fix:
          "Add WebSocket server alongside the existing HTTP server. Push notifications to connected clients when background jobs complete.",
        files_to_modify: [
          "src/server.ts",
          "src/websocket/handler.ts",
          "src/services/notifications.ts",
        ],
        tests_needed: "WebSocket connection tests, notification delivery tests",
        action_plan: [
          "Set up WebSocket server in server.ts",
          "Create notification handler",
          "Integrate with background job completion events",
        ],
        risks: ["WebSocket scaling with multiple server instances"],
        open_questions: [
          "Should we use Socket.IO or native WebSocket API?",
          "Do you want per-user notification channels or a single broadcast?",
          "Should notifications persist in the database or be ephemeral?",
        ],
      },
      files_info: [
        { path: "src/server.ts", lines: 89 },
        { path: "src/websocket/handler.ts", lines: null },
        { path: "src/services/notifications.ts", lines: null },
      ],
      fix_progress: null,
      blocker: null,
      pr: null,
      steps: [],
      messages: [],
      scoping_session: {
        session_id: "demo-scope-20",
        session_url: "https://app.devin.ai/sessions/demo-scope-20",
        started_at: "2026-02-07T10:00:00Z",
      },
      fix_session: null,
      last_devin_comment_id: 123456789,
      last_devin_comment_at: "2026-02-07T10:15:00Z",
      github_comment_url: "https://github.com/natan/devin-issue-pilot-demo/issues/20#issuecomment-123456789",
      forwarded_comment_ids: [],
      scoped_at: "2026-02-07T10:15:00Z",
      fix_started_at: null,
      completed_at: null,
    },
  ];
}
